### ISSUE TITLE
Cài đặt công cụ

### ISSUE THREAD

**Issue by trinhtienschool** [trinhtienschool/GreenTeaWebAPI#1]
Cài phpstorm, Cài xampp, đăng kí mdb pro: deadline 22h: 31/12/2021
Tìm hiểu Github copilot (không bắt buộc)
Hình thức nộp bài: chụp màn hình mỗi phần đã làm vào phần comment bên dưới. Mỗi phần ít nhất 1 hình chụp. Cụ thể sau khi cài xong phpstorm thì chụp tối thiểu 1 hình về màn hình của phpstorm, xampp, mdb pro tương tự.

**Comment by phanhuuthang1612** [comment]
https://drive.google.com/drive/folders/1CY0LSYhJCP_cawcra_uoiqurgPJzCy0i?usp=sharing

3 màn hình PHP, xampp, đăng ký thành công MDB pro

**Comment by trinhtienschool** [comment]
Anh nộp phần của anh nhé
![image](https://user-images.githubusercontent.com/80469671/147823712-0f35d660-fafc-4a3e-b85f-200a00b460f6.png)
![image](https://user-images.githubusercontent.com/80469671/147823745-5e52bfa6-1d96-4c66-ada9-3db68ae08fdf.png)
![image](https://user-images.githubusercontent.com/80469671/147823820-82769316-f496-4725-ad3a-2d807cc608f9.png)
![image](https://user-images.githubusercontent.com/80469671/147823851-90a3e5f5-fdae-4d3d-84e3-c8c9a8a777db.png)

**Comment by tranhuudan-02573** [comment]
dạ em Dân ạ
![image](https://user-images.githubusercontent.com/76217449/147824076-eae4f479-fffa-4d92-8ec4-27c94c7bee91.png)
![image](https://user-images.githubusercontent.com/76217449/147824106-9ecdb33b-6351-4f98-804e-825a8a2b1a43.png)
![image](https://user-images.githubusercontent.com/76217449/147824110-6e01ac12-689c-4e52-965c-a25f60480d39.png)

**Comment by DuongThiMinhNhu** [comment]
em nộp ạ
![Facebook - Google Chrome 31_12_2021 20_09_32](https://user-images.githubusercontent.com/76153599/147825116-c5709807-6213-472a-bcca-cecbdfbdabb3.png)
![Tack1 31_12_2021 20_08_47](https://user-images.githubusercontent.com/76153599/147825118-3732f3c7-40c0-491e-a34f-054210dd954d.png)
![XAMPP Control Panel v3 3 0     Compiled_ Apr 6th 2021   31_12_2021 20_09_11](https://user-images.githubusercontent.com/76153599/147825119-f5659f29-f86f-4c5d-ae37-e56cd95e9cc9.png)

**Comment by thanhnguyenle** [comment]
![image](https://user-images.githubusercontent.com/76036506/147833467-3a62698d-36e3-4f3c-820e-5963f78d0ae7.png)
![image](https://user-images.githubusercontent.com/76036506/147833477-745a8dd9-71d3-4e38-887d-9f190b36ce6a.png)
![image](https://user-images.githubusercontent.com/76036506/147833654-d934916e-45fc-4a2c-a857-415163976621.png)
Chúc mừng năm mới a Tiến, e cố tình nộp muộn một chút để gửi lời chúc cũng như tặng quà năm mới cho a là 3 tấm ảnh này đó :)

**Comment by trinhtienschool** [comment]
> ![image](https://user-images.githubusercontent.com/76036506/147833467-3a62698d-36e3-4f3c-820e-5963f78d0ae7.png) ![image](https://user-images.githubusercontent.com/76036506/147833477-745a8dd9-71d3-4e38-887d-9f190b36ce6a.png) ![image](https://user-images.githubusercontent.com/76036506/147833654-d934916e-45fc-4a2c-a857-415163976621.png) Chúc mừng năm mới a Tiến, e cố tình nộp muộn một chút để gửi lời chúc cũng như tặng quà năm mới cho a là 3 tấm ảnh này đó :)

Cảm ơn em, đây là dấu hiệu của sự lươn lẹo! 😂😂😂

**Comment by trinhtienschool** [comment]
OK, vậy mình kết thúc issues 1 nhé!
