### ISSUE TITLE
Cài laravel

### ISSUE THREAD

**Issue by trinhtienschool** [trinhtienschool/GreenTeaWebAPI#2]
Cài laravel để chạy được trong phpstorm, Tích hợp mdb trong laravel project, Tạo hello world laravel, có sử dụng 1 component bất kì của mdb: **deadline 22h: 1/1/2021**
Hình thức nộp bài, tạo 1 branch với tên mình và push code hello world lên đây, và chụp màn hình của kết quả chạy hello world paste vào phần comment bên dưới

**Comment by trinhtienschool** [comment]
Anh nộp bài hôm nay: 
![image](https://user-images.githubusercontent.com/80469671/147834220-bf01d206-cc5b-421a-bf32-53e7a561537c.png)

**Comment by trinhtienschool** [comment]
**Gợi ý cách làm:** 
**Import mdb:**
 Sau khi đã đăng kí thành công mdb pro, đảm bảo trình duyệt đang đăng nhập vào mdb sau đó vào [my-order](https://mdbootstrap.com/profile/my-orders/) sau đó chọn gói mdb4 pro và bấm vào nút xanh để download.
![image](https://user-images.githubusercontent.com/80469671/147834468-fb7315a1-ced0-4972-a887-c7ad078a05b3.png)
Sau copy các file css và js vào thư mục theo như hình 
![image](https://user-images.githubusercontent.com/80469671/147834517-25a05193-089e-4f26-af71-c6705765e646.png)

**Tạo project trong phpstorm:** [create project with composer](https://www.jetbrains.com/help/phpstorm/using-the-composer-dependency-manager.html#working-with-composer-json)
**Run project:** 
Có nhiều cách run project
- Nếu đã cài đặt môi trường composer rồi thì chỉ cần gõ đường link dẫn đến thư mục project/public/{routing}
- Nếu muốn cài đặt server chạy thì làm theo hình:
![image](https://user-images.githubusercontent.com/80469671/147834782-7ac5f837-678b-4164-91e8-9c31e87b6334.png)
Bấm vào (1) chọn Edit...
Bấm vào (2) chọn php build-in web server
Bấm vào (3) chọn đường dẫn đến xampp/{project-name}/public

**Comment by tranhuudan-02573** [comment]
em Dân ạ
![image](https://user-images.githubusercontent.com/76217449/147854308-435bb805-1a6c-492d-9549-6c660e795069.png)

**Comment by DuongThiMinhNhu** [comment]
- [ ] #

1. 

- [ ]

**Comment by DuongThiMinhNhu** [comment]
[``](url)

**Comment by DuongThiMinhNhu** [comment]
![Material Design Bootstrap Template - Google Chrome 01_01_2022 23_33_27](https://user-images.githubusercontent.com/76153599/147855314-8a69463e-e4f6-4056-b852-161c691a6843.png)
em bo login

**Comment by thanhnguyenle** [comment]
anh Tiến ơi hôm nay em ham chơi quá chưa hoàn thành xong kịp cái deadline cho e ngày mai nộp nha

**Comment by thanhnguyenle** [comment]
![image](https://user-images.githubusercontent.com/76036506/147865283-2f22889f-37d2-48fd-af67-2accd4146a13.png)

**Comment by trinhtienschool** [comment]
ok, hình của Thắng nộp bên group chat zalo rồi, nên anh close issues luôn nhé
