### ISSUE TITLE
Tìm hiểu Architecture Concepts

### ISSUE THREAD

**Issue by trinhtienschool** [trinhtienschool/GreenTeaWebAPI#3]
Tìm hiểu component, routing, controller, view(tìm hiểu cơ bản, không cần chuyên sâu), sau đó làm viết 1 app đơn giản theo mô hình MVC có request và trả về 1 view đơn giản (không cần phải có template, chỉ cần có request, trả về text cũng được) **deadline: 22h 2/1/2021.**
Hình thức nộp bài: push code lên branch đã tạo ở issus 2 (có thể dùng lại project của branch đó, không cần tạo project mới) và chụp màn hình code và kết quả, paste ở comment, ít nhất 3 hình

**Comment by trinhtienschool** [comment]
Tóm tắt tài liệu tham khảo:
[Vòng đời request của laravel](https://viblo.asia/p/tap-5-vong-doi-request-laravel-request-lifecycle-laravel-LzD5dwqOljY)
[Tạo ứng dụng mô hình mvc trong laravel](https://techmaster.vn/posts/34656/tao-ung-dung-mvc-co-ban-voi-laravel-5-trong-10-phut)
[Controller](https://laravel.com/docs/8.x/controllers)
[Routing](https://laravel.com/docs/8.x/routing)
[Blade template](https://laravel.com/docs/8.x/blade)
[View](https://laravel.com/docs/8.x/views)

**Comment by phanhuuthang1612** [comment]
https://drive.google.com/drive/folders/1Cx60VUWNQMg1ElqpJBfZmBhGXscvNQtf?usp=sharing

Hình cho issues 3
-----------------------------------------------
![view](https://user-images.githubusercontent.com/76423055/147879406-a06d1060-af30-4743-88ba-e121982be728.png)
![route](https://user-images.githubusercontent.com/76423055/147879409-0dcc965d-2f0d-47c3-b632-ed3ac77722aa.png)
![controller](https://user-images.githubusercontent.com/76423055/147879416-5e4efaca-ea40-4e19-849d-af7223e0b9c3.png)

![code_controller](https://user-images.githubusercontent.com/76423055/147879420-16b09b33-948d-4cbc-8c4d-930bb890d800.png)

![code_controller_route](https://user-images.githubusercontent.com/76423055/147879422-864e410f-5943-4ca8-9aff-95eb2117568e.png)

**Comment by trinhtienschool** [comment]
Hình cho issues 3:
![image](https://user-images.githubusercontent.com/80469671/147879074-ff85addf-214e-4713-acd1-56d8f72aaf88.png)
![image](https://user-images.githubusercontent.com/80469671/147879080-8b5ed252-63d7-40c6-9fbf-1f525927500a.png)
![image](https://user-images.githubusercontent.com/80469671/147879083-7724c3b9-c9c3-4dfe-8e1a-95071775e922.png)
![image](https://user-images.githubusercontent.com/80469671/147879084-5e808992-5f7b-4e70-bc38-0b03457e335f.png)
![image](https://user-images.githubusercontent.com/80469671/147879085-d3103130-f833-4d30-9dad-44b54fea0671.png)

**Comment by trinhtienschool** [comment]
> https://drive.google.com/drive/folders/1Cx60VUWNQMg1ElqpJBfZmBhGXscvNQtf?usp=sharing
> 
> Hình cho issues 3

Thắng hình như em chưa push code lên github của issues 3 này á em

**Comment by trinhtienschool** [comment]
![image](https://user-images.githubusercontent.com/80469671/147879285-bf1e4f7d-f7af-4ef5-8d16-7bf7da8a2f6f.png)

**Comment by tranhuudan-02573** [comment]
dạ em Dân ạ
![image](https://user-images.githubusercontent.com/76217449/147884023-26447cc9-21be-409d-b3fb-dac6b1c4dde6.png)
![image](https://user-images.githubusercontent.com/76217449/147884025-1a235bb3-6d68-465f-8170-0d0a51a079da.png)
![image](https://user-images.githubusercontent.com/76217449/147884027-9e244afa-5e9f-4e7f-89bb-5879dc50337d.png)

**Comment by thanhnguyenle** [comment]
![image](https://user-images.githubusercontent.com/76036506/147899440-3cde020c-6bd0-409a-be85-5f566b7863c4.png)
![image](https://user-images.githubusercontent.com/76036506/147899446-cc745b3d-baf7-4b61-9786-bcc28334c208.png)
![image](https://user-images.githubusercontent.com/76036506/147899472-d4abc65d-677a-4d61-a3f9-4378db18664a.png)

**Comment by DuongThiMinhNhu** [comment]
![Uploading Material Design Bootstrap Template - Google Chrome 04_01_2022 18_00_58.png…]()

**Comment by DuongThiMinhNhu** [comment]
![Material Design Bootstrap Template - Google Chrome 01_01_2022 23_33_27](https://user-images.githubusercontent.com/76153599/148049857-4fb81a37-734e-44de-8097-ce73357af86d.png)
![Tack1 – web php 04_01_2022 18_02_04](https://user-images.githubusercontent.com/76153599/148049860-1078e416-e886-4d4b-a1fa-9cf04251e34d.png)
![Tack1 – web php 04_01_2022 18_01_32](https://user-images.githubusercontent.com/76153599/148049863-6496bba5-572e-40c1-9646-4a2f4244598a.png)
![Material Design Bootstrap Template - Google Chrome 04_01_2022 18_01_18](https://user-images.githubusercontent.com/76153599/148049865-fe5193b4-f4fe-458f-bedd-8d38e3a59e48.png)

**Comment by DuongThiMinhNhu** [comment]
![Material Design Bootstrap Template - Google Chrome 04_01_2022 18_00_58](https://user-images.githubusercontent.com/76153599/148049923-43fb9e62-6ac2-437e-b9de-10270a849fe4.png)
