### ISSUE TITLE
Laravel demo application: sign in & sign up

### ISSUE THREAD

**Issue by trinhtienschool** [trinhtienschool/GreenTeaWebAPI#4]
Làm tính năng đăng nhập và đăng kí: code đơn giản có sử dụng mdb, có truy xuất database (mysql). **Deadline: 22h 4/1/2021**
Hình thức nộp bài: push code lên branch đã tạo ở issus 2, và chụp màn hình code và giao diện trên browser, paste và phần comment, ít nhất 3 hình

**Comment by DuongThiMinhNhu** [comment]
![Tack1 – LoginController php 04_01_2022 20_42_22](https://user-images.githubusercontent.com/76153599/148068193-c2ef09e1-3edf-4aaa-be59-39907590f2ec.png)
![Material Design Bootstrap Template - Google Chrome 04_01_2022 20_45_00](https://user-images.githubusercontent.com/76153599/148068194-09b227b1-49dc-4811-93cc-7d7bc6576d68.png)
![Material Design Bootstrap Template - Google Chrome 04_01_2022 20_44_51](https://user-images.githubusercontent.com/76153599/148068197-f4119b2b-0434-45b9-b154-150427f26915.png)
![Material Design Bootstrap Template - Google Chrome 04_01_2022 20_44_40](https://user-images.githubusercontent.com/76153599/148068201-7602c896-e90b-46e0-a392-aa74487f0393.png)
![Tack1 – LoginController php 04_01_2022 20_42_37](https://user-images.githubusercontent.com/76153599/148068205-653cdd0a-affc-483e-8ddf-87a22fb7b2b7.png)

**Comment by trinhtienschool** [comment]
Sorry mấy em, code anh làm không auth, code login để hack tìm tòi, =))
![image](https://user-images.githubusercontent.com/80469671/148077455-f0e093e9-4d87-4b5a-8571-b0b427521019.png)
![image](https://user-images.githubusercontent.com/80469671/148077474-3d73685f-6856-4b57-883b-c80b47216522.png)
![image](https://user-images.githubusercontent.com/80469671/148077498-42897795-a188-412e-83c6-2a77a0db19cc.png)
![image](https://user-images.githubusercontent.com/80469671/148077515-9628ac16-dabd-4380-b346-25ffe66d4894.png)
![image](https://user-images.githubusercontent.com/80469671/148077528-7b0736a2-e837-4ae6-9e84-7972d42eab06.png)
![image](https://user-images.githubusercontent.com/80469671/148077535-bc426776-3ccd-4af5-9d50-36a8cfa0d274.png)

**Comment by phanhuuthang1612** [comment]
![register](https://user-images.githubusercontent.com/76423055/148086245-f1de8613-a809-47a6-bf1b-b55c6d1cf054.png)
![login](https://user-images.githubusercontent.com/76423055/148086264-0e58a1a9-c894-4da9-b024-1e5e72c54684.png)
![loginSuccess](https://user-images.githubusercontent.com/76423055/148086287-00fde901-a92c-4962-ace3-6293fc447be7.png)
![database](https://user-images.githubusercontent.com/76423055/148086309-267fdc9a-828d-4a25-8939-7db992b60970.png)
---------------okiiiiii !!! love u so much..............

**Comment by thanhnguyenle** [comment]
Sorry vì em nộp muộn, nhưng được cái là khá kĩ
Màn hình login
![image](https://user-images.githubusercontent.com/76036506/148195020-88dbe841-462b-40a5-a502-c13055c89107.png)
Check điều kiện chưa nhập username, hoặc tài khoản chưa được đăng kí
![image](https://user-images.githubusercontent.com/76036506/148195129-10beff81-d814-44c7-880b-2b2b113f210f.png)
Màn hình đăng kí
![image](https://user-images.githubusercontent.com/76036506/148195703-3af4beaf-b93b-4e1a-ae76-16482fb4caf6.png)
Check điều kiện chưa nhập username,username đã đăng kí
![image](https://user-images.githubusercontent.com/76036506/148195913-d954e1d2-360f-4f5b-b12a-89f87a004b5b.png)
Check điều kiện password xác nhận không khớp với password đã đặt
![image](https://user-images.githubusercontent.com/76036506/148196084-3f5168b3-a135-417e-b720-bac2cefc9374.png)
Lưu dữ liệu vào database khi đăng kí thành công
![image](https://user-images.githubusercontent.com/76036506/148196310-b974efd8-f1d9-41f7-9e54-dcc9d97310ba.png)
Xem được list user khi đăng nhập thành công
![image](https://user-images.githubusercontent.com/76036506/148196441-7406714a-09b2-4623-a6ae-54c68f170876.png)
Khi chưa login mà đòi xem profile thì sẽ như thế này
![image](https://user-images.githubusercontent.com/76036506/148197138-760e4c79-9bed-43f0-a2a2-45ee5541d7c2.png)

**Comment by tranhuudan-02573** [comment]
![image](https://user-images.githubusercontent.com/76217449/148395132-45b71ede-940a-4f9a-a1ab-ef4fbe203f2f.png)
![image](https://user-images.githubusercontent.com/76217449/148395958-c0bb6c19-e01c-4a6f-912f-8be63101e3fd.png)
![image](https://user-images.githubusercontent.com/76217449/148395167-f388f8da-8be9-4a73-b6f1-d1431f644b25.png)
![image](https://user-images.githubusercontent.com/76217449/148395247-b36ff682-d8a0-4c66-8141-4742dda91507.png)
![image](https://user-images.githubusercontent.com/76217449/148395373-2b27e907-f9f2-4322-8b28-fa01f1e6d6d4.png)
![image](https://user-images.githubusercontent.com/76217449/148395592-82305439-972e-4acc-9248-019eb0690659.png)
![image](https://user-images.githubusercontent.com/76217449/148398275-45644572-d2f1-4460-9edf-89177450534d.png)

**Comment by trinhtienschool** [comment]
Mình làm xong issue này rồi, vậy anh đóng nó lại luôn nhé
